// File auto-generated by build_version.js
/* eslint-disable eol-last */
module.exports = {
  'version': '2020.2.0',
  'year': 2020,
  'month': 2,
  'buildTotal': 7,
  'buildThisYear': 6,
  'buildThisMonth': 0
}
