// File auto-generated by build_encryptees.js
// used eKeyIndex: 8
module.exports = [
  'NebLXNUgsvR+UBeQxFaqhN1Ldk/lRl0C22L5nrCo2gKo', // 0: core.userscriptUi
  'Sitwkv7YvEt4MsONLT0dKmcsKQXYG4jWci6whpKoOxDE7TY='  // 1: wifiBasicFormSubmit
]
