// File auto-generated by build_encryptees.js
// used eKeyIndex: 8
module.exports = [
  'YDHieuK8u3MqnbUSKSAZ6Ul95Wf67uyFTqO6BBiXaVvMTe33cqIf9Q==', // 0: KORIANFREEWIFIAUTOLOGINU
  'wVbQvkCH/Ti14CwAFkXCt510vfbXYCFcIjLWk3Il97h9+uuV9h6VKEY2EebcLAC7QM4l6ztmabIDc0WqpdoMBdYM14DA0QsD8yM+Z6zGvO+VFw=='  // 1: https://github.com/rsouverain/KORIAN_wifipass_autologin_userscript
]
